### PR TITLE
#10 fix mongodb Id

### LINKED ISSUE #10: Fix FindById in all of the entity classes
### **Issue**

- After migrating to MongoDB, the Id of all the Entity (Model) classes are mapped with a unique ObjectId, making findById not work anymore as an endpoint. 

image
image

### PR DESCRIPTION
**Pull request by qihongw08**
- Added NextSequence Service to assign numeric IDs to Quotes when populating the database from API. 
- Added conditional statement in apiService, fetch from API only if the DB is empty 
- Made minor changes to Entity classes' properties. 

Related Front End PR: https://github.com/quntao-z/bliss-frontend/pull/2

Closes #10

### CODE REVIEW

File: src/main/java/com/bliss/blissapp/Repository/QuoteRepository.java [hunk 1]
```diff
@@ -2,6 +2,12 @@
 
 import com.bliss.blissapp.Model.Quote;
 import org.springframework.data.mongodb.repository.MongoRepository;
+<<<<<<< HEAD
```
Comment (quntao-z) [inline src/main/java/com/bliss/blissapp/Repository/QuoteRepository.java:5]: merge conflicts

**Review by quntao-z — CHANGES_REQUESTED** [review]
Please fix merge conflicts

**Review by quntao-z — APPROVED** [review]
